### ISSUE TITLE
Issue #03 - Schema

### ISSUE THREAD

**Issue by keginzburg** [KevinTungDHR/Relay#3]
# Database Schema
- [X] Contains correct datatypes
- [X] Contains appropriate constraints/details
  - [X] primary key
  - [X] not null
  - [X] unique
  - [X] indexed
  - [X] foreign key
- [X] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [X] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
  - [X] schema is written in a table format
  - [X] the table’s name are lowercased, snake_cased and `back_ticked`
  - [X] the table header column names are bolded
  - [X] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

I believe I see how you are going about subscribing your messages to specific Channels, DMs, Group Chats, and Threads, but I think the actual writing in this design document needs some clarification:

1. Subscriptions
    1. If a subscription is working as a join between users and their relevant workspace, channel, group chat, then does a subscription also belong to a specific user?
2. Workspaces
    1. owner row should be owner_id
    2. Do workspaces have many members through subscriptions? Below tables should also keep track of through associations.
3. Channels
    1. You are specifying an association between users and channel via an Admin row (maybe change to admin_id in row), but also giving each channel a unique id for the workspace it belongs to. Is the workspace_id completely necessary? If so, how do you plan to provide that when an admin creates a new channel?
    2. Does a channel have many members through subscriptions? Your association just lists has_many members.
4. Direct Chat
    1. You are utilizing two foreign keys to specify which two users are in a direct chat, but your association for users is a has_many? Should this be a belong_to? This is essentially a joins table, is it not?
    2. Again, use of workspace_id here (see above).
5. Group Chat
    1. Use of workspace_id here (see above).
6. Threads
    1. Use of workspace_id here (see above).
    2. Change parent_message to parent_message_id and provide a relevant association for that foreign key.
    3. Interested to see if you can organize these nested messages via just the parent_message_id and that message’s relevant polymorphic association. Excited to see the results.

**Comment by KevinTungDHR** [comment]
I've updated the schema to reflect your comments:
*Every single table has more detailed and clear associations

1. Subscriptions
i. I may have misunderstood but my original subscriptions had a user_id to show which user a subscription belongs to, however it might have been more clear had I used more semantic name like subscriber_id
2.  Workspaces
i. Workspace owner row has been changed to owner_id
ii. Updated space below workplace table show associations
3. Channels
i. I believe the workspace_id is necessary because every type of chat (channel, dm, group, thread) belongs to a specific workplace. Closing a workspace means you don't have access to those chats/groups/users anymore. Based off how slack works I noticed that the workspace id is embedded in the url. In terms of getting the id my current plan was this:
   1. When the admin creates a new channel we grab the url wildcards params. 
   2. In the backend we find that workspace and check that the user is in fact part of the workspace they are trying to create a channel for through an association  
   
   ii. Added associations and details to has_many members
4. Direct Chat
i. Ah! Yes, this is essentially a joins table which actually made me remember what the whole point of my subscriptions was for. I actually don't need user_ids I can do the same thing I'm doing with group chats except add a validation of `validates_length_of :users maximum: 2` I'm not 100% sure if this will work but it's something I'm going to need to test out. I want all of the different chat rooms to be under the subscriptions so that I am able to query easily if needed
6. Threads
ii. parent_message changed to parent_message_id and association provided
iii. Me too...

In regards to 3, 4, 5 and 6, please let me know if my workspace_id makes sense.
