### ISSUE TITLE
Issue #05 - Backend Routes

### ISSUE THREAD

**Issue by keginzburg** [KevinTungDHR/Relay#5]
# Backend Routes
- [X] Contains the following sections: HTML, API Endpoints(Backend)
- [X] Each route has a description
- [X] API Endpoint routes contains wildcard variables written in `snake_case`
- [X] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [X] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn’t need a `GET likes` api endpoint because that info comes through the post show

## Comments
Some questions below to gain a better understanding of your backend workflow:

Users

1. Do you think you might need a GET route for getting a specific user’s information? Or maybe another GET route when searching for a user?

Subscriptions

1. What do you mean by CRUD subscriptions routes?
2. As for get all the subscriptions for a user, should this route potentially be nested under your users routes? What might that provide you in the URI pattern?

Workspace

1. Same goes for getting a workspace related to a user (not the ones currently open). How will we know whose workspaces we are trying to retrieve from our backend?

Channel

1. Do we want a GET route for individual channels, so we don’t need to pull all channels every time we check a single channel?

Direct Chat/Groups

1. Do we want a GET route for individual Direct Chats/Group Chats? Also, do we want the ability to update Direct Chats or only Group Chats?

Threads

1. Similar to above, how will we know which threads we want in our GET /api/threads route. Won’t this pull all the threads every time? Do we want to nest this under another route?

Messages

1. Do we want to be able to get specific messages? Or just all messages for a relevant thread/DC/GC/channel? And do we want the ability to delete individual messages?

**Comment by KevinTungDHR** [comment]
Users
1. I will probably need a GET route for searching for a particular user but as of now searching is part of my bonus features (hopefully one of the first ones I get to). I'm unsure at this point how necessary it will be to have a get route for a specific user or if that information will be fetched when I'm fetching subscriptions


Subscriptions
1. I was overthinking this. When I create/update/delete from the models the joins will be destroyed due to dependent destroy.
2. After working on the action_cable_demo from AppAcademyOpen things are slightly clearer. The demo uses a fetchRoom(roomId) and get all the slice information through associations and jbuilder. I need to do the exact same thing but on a larger scale. My 'room' is actually the workspace and I'll need to make an initial fetch for a specific workspace for all the users, subscribed channels, subscribed messages and then have each of those subscriptions, or MessageIndexItem, subscribe to my Action Cable when the component mounts. Because of this I've removed the subscriptions routes entirely as they are doing essentially what I want my workspace routes to be doing.

Workspace
I have two GET routes now for workspaces:
1. One for getting all subscribed workplaces. My plan is to check for optional parameters for if we are checking for subscribed & currently open workspaces or all subscribed workplaces
2. The second is the most important and will be how I fetch all the related message data when a user first connects to a workspace. This is important because all the channels/dms/groupchats must connect to ActionCable at the start.

Channel
1. I've made the GET route for only an individual channel when they first subscribe. I never need to pull all channels except for when they first open up the chat client and that will be fetched through associations from my fetchWorkspace as mentioned above

Direct Chat/Groups
1. Same as channel, I added a direct chat get route for individual chats on first subscription. I removed the GET route for groups because outside of the initial fetch I don't believe you would ever need to GET messages on subscription because slack starts a blank conversation when you get added to a group.

Threads
1. I've removed the GET route as it was originally to get all threads for when they use the Thread search feature but it should all be in state which will be updated through action cable.

Messages
1. I don't think we ever need to get a specific message. 
2. I don't actually believe I need to ever get all messages through this manner. 
3. On further research it appears you can't delete slack messages. 
All three of those routes have been deleted

Apologies for such a messy edit. I hope it's comprehendible
